name: rnaquarium-figs
channels:
 - conda-forge
dependencies:
 - jupyterlab>=4.2.1
 - matplotlib>=3.9.1
 - conda-forge::pandas=2.2.3
 - python=3.12
 - ruff
 - shellcheck
 - plotly=5.24.1
 - bioconda::entrez-direct
 - ca-certificates
 - certifi
 - openssl
 - polars
 - conda-forge::pyarrow
 - conda-forge::seaborn
 - conda-forge::upsetplot
 - great_tables
 - intervaltree
 - bedtools